# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.7.0
_src_path: gh:algorandfoundation/algokit-python-template
author_email: hamzaismati2@gmail.com
author_name: Rqppid
contract_name: hello_world
deployment_language: python
preset_name: starter
project_name: smart_contracts

